bugfix: use separate regexes for each packet type
because it's hard to generalize. sometimes it's a just a hex numeric
value, sometimes it's a blob in little endian order. and this, for
example, fails:

» "m400,2"

Error: (make-string) bad argument type - not a fixnum: 3/2