bugfix: remove bad string-prefix?
First off, this needs the minimum of the string lengths supplied. But
then it just becomes the same procedure as substring=?. I don't know
why it was introduced in the first place.

This gets rid of error messages like this:

     » "Hc0"

    Error: (substring=?) out of range
    6
    0
    4